config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get 'users/sign_out', to: "devise/sessions#destroy"
    delete '/cancel_account', to: 'registrations#cancel_account', as: 'cancel_account'

  end

  
  resources :poem_posts
  resources :poem_posts do
    resources :comments, only: [:create, :destroy]
  end

  root 'static_page#index'
  get '/home', to: 'poem_posts#index'
  get '/writing', to: 'poem_posts#new'
  get '/poem_posts/:id', to: 'poem_posts#show'
  patch '/poem_posts/:id', to: 'poem_posts#update'
  delete '/poem_posts/:id', to: 'poem_posts#destroy'
  get '/poem_posts/:id/edit', to: 'poem_posts#edit'
  post '/writing', to: 'poem_posts#create'
  get '/profile', to: 'static_page#profile'
get '/profile/edit', to: 'static_page#edit', as: 'edit_profile'
patch '/profile', to: 'static_page#update', as: 'update_profile'
get 'search', to: 'search#index', as: 'search'







end

app/models/poem_post.rb
class PoemPost < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true, allow_blank: true
    belongs_to :user
 has_many :comments, dependent: :destroy
       
      
end

app/controllers/poem_posts_controller.rb
class PoemPostsController < ApplicationController
    def index
      @poem_posts = PoemPost.all
    end
    
    def show
      @poem_post = PoemPost.find(params[:id])
    end
  
    def new
      @poem_post = PoemPost.new
    end
  
    def create
      @poem_post = current_user.poem_posts.build(poem_post_params)
      if @poem_post.save
      redirect_to home_path
      else
        render :new, status: :unprocessable_entity 
      end
    end

    def destroy
      @poem_post = PoemPost.find(params[:id])
      @poem_post.destroy
      redirect_to @poem_post
    end
    

    def edit
@poem_post = PoemPost.find(params[:id])
    end

    def update
        @poem_post = PoemPost.find(params[:id])
        if @poem_post.update(poem_post_params)
        redirect_to @poem_post
        else
        render :edit, status: :unprocessable_entity 
        end
    end

  
    private
  
    def poem_post_params
      params.require(:poem_post).permit(:title, :content)
    end
  end
  

app/views/poem_posts/_form.html.erb
<%= form_with model: @poem_post do |form| %>
<% if form.object.errors.any? %>
<div>
<% form.object.errors.full_messages.each do |message| %>
<div><%= message%></div>
<% end %>
</div>
<% end %>

<div>
  <%= form.text_field :title, placeholder: "Title", class: "title-field" %>
</div>

<div class="poem-posts-new-container">
<%= form.text_area :content, :class => "tinymce", :rows => 35, :cols => 70 %>
<%= tinymce %>
<div>

<%= form.button "Submit", class: "writingbutton" %>
<% end %>

app/views/poem_posts/edit.html.erb
<h1> Made a mistake? No Problem! </h1>

<%= render partial: "form", locals:{poem_post: @poem_posts} %>

app/views/poem_posts/index.html.erb
<body class="scroll-container">
  <div class="row">
    <% @poem_posts.each do |poem_post| %>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title"><%= link_to poem_post.title, poem_post_path(poem_post), style: 'color: black; text-decoration: none;' %></h2>
            <div class="card-content">
              <%= raw poem_post.content %>
            </div>
            <p class="card-footer"> 
            Written by:<%= link_to poem_post.user.username, profile_path(poem_post.user), style: 'color: black; text-decoration: none;' %>
            <p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</body>

app/views/poem_posts/new.html.erb
<%= render partial: "form", locals:{poem_post: @poem_posts} %>

app/views/poem_posts/show.html.erb
</html>
<head>
</head>
<body class="scroll-container">
<div class="col-sm-6">
<div class="card-container-show">
<div class="card-show">
<div class="card-body-show">
 <div class="card-content-show">
 <h1><%= @poem_post.title %></h1>
<%= raw @poem_post.content %>
</div>
</div>
</div>
</div>
<% if current_user && current_user == @poem_post.user %>
<div class="edit-delete-container">
  <%= link_to 'Edit', edit_poem_post_path(@poem_post) %>
    <%= button_to 'Delete', @poem_post, method: :delete,class: "btn btn-danger" %>
     </div>
<% end %>
</div>

<div class="col-sm-6">
<div class="comments-section">
    <h2>Comments</h2>

    <% @poem_post.comments.each do |comment| %>
 <div class="comment">
  <div class="comment-header">
    <%= link_to(profile_path(comment.user)) do %>
      <%= comment.user.username %>
    <% end %>
     <%= link_to "Delete", poem_post_comment_path(@poem_post, comment), method: :delete, class: "delete-link" %>
  </div>
  <div class="comment-content">
    <%= raw comment.content %>
  </div>
</div>

<% end %>

    <%= render partial: 'comments/form', locals: { comment: Comment.new, poem_post: @poem_post } %>

  </div>
</div>
</div>

</body>
</html>