config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get 'users/sign_out', to: "devise/sessions#destroy"
    delete '/cancel_account', to: 'registrations#cancel_account', as: 'cancel_account'

  end

  
  resources :poem_posts
  resources :poem_posts do
    resources :comments, only: [:create, :destroy]
  end

  root 'static_page#index'
  get '/home', to: 'poem_posts#index'
  get '/writing', to: 'poem_posts#new'
  get '/poem_posts/:id', to: 'poem_posts#show'
  patch '/poem_posts/:id', to: 'poem_posts#update'
  delete '/poem_posts/:id', to: 'poem_posts#destroy'
  get '/poem_posts/:id/edit', to: 'poem_posts#edit'
  post '/writing', to: 'poem_posts#create'
  get '/profile', to: 'static_page#profile'
get '/profile/edit', to: 'static_page#edit', as: 'edit_profile'
patch '/profile', to: 'static_page#update', as: 'update_profile'
get 'search', to: 'search#index', as: 'search'







end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_one_attached :image
  has_one_attached :banner_image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :poem_post
  belongs_to :user
end

app/models/poem_post.rb
class PoemPost < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true, allow_blank: true
    belongs_to :user
 has_many :comments, dependent: :destroy
       
      
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :poem_posts, dependent: :destroy
  has_one_attached :image
  has_one_attached :banner_image



  def destroy_associated_poem_posts
    poem_posts.destroy_all
  end

  def user_params
    params.require(:user).permit(:username)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home
    @poems = Poem.all
    render "static_page/home"
  end
  
  
   def after_sign_in_path_for(resource)
        home_path
      end
    
      def after_sign_up_path_for(resource)
        home_path
      end

    
      
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
  def create
    @poem_post = PoemPost.find(params[:poem_post_id])
    @comment = @poem_post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to poem_post_path(@poem_post), notice: "Comment created successfully."
    else
      redirect_to poem_post_path(@poem_post), alert: "Error creating comment."
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.poem_post, notice: "Comment was successfully deleted."
  end
  
  def show
    @poem_post = PoemPost.find(params[:id])
    @comment = Comment.new
    @form = Form.new 
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/poem_posts_controller.rb
class PoemPostsController < ApplicationController
    def index
      @poem_posts = PoemPost.all
    end
    
    def show
      @poem_post = PoemPost.find(params[:id])
    end
  
    def new
      @poem_post = PoemPost.new
    end
  
    def create
      @poem_post = current_user.poem_posts.build(poem_post_params)
      if @poem_post.save
      redirect_to home_path
      else
        render :new, status: :unprocessable_entity 
      end
    end

    def destroy
      @poem_post = PoemPost.find(params[:id])
      @poem_post.destroy
      redirect_to @poem_post
    end
    

    def edit
@poem_post = PoemPost.find(params[:id])
    end

    def update
        @poem_post = PoemPost.find(params[:id])
        if @poem_post.update(poem_post_params)
        redirect_to @poem_post
        else
        render :edit, status: :unprocessable_entity 
        end
    end

  
    private
  
    def poem_post_params
      params.require(:poem_post).permit(:title, :content)
    end
  end
  

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        @query = params[:query]
        @users = User.where("username LIKE ?", "%#{@query}%")
        @poems = PoemPost.where("title LIKE ?", "%#{@query}%")
      end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index
  end

  def home
  end

  def writing
  end

  def profile
  end

  def edit
    @user = current_user # Fetch the user's profile information
  end

  def update
    if current_user.update(user_params)
      flash[:notice] = "Profile updated successfully."
      redirect_to profile_path
    else
      flash[:alert] = "Profile update failed."
      render :edit
    end
  end
  
  def user_params
    params.require(:user).permit(:username, :bio, :location, :image, :banner_image)
  end
  
 
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
   
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oète</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
   <%= stylesheet_link_tag 'index', 'profile', 'devise', 'writing', 'editprofile',"search","comments", media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter&display=swap">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Serif+Pro&display=swap">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'tinymce' %>
  <script type="text/javascript" src="/assets/tinymce.js"></script>
</head>

<body>
<div id="notification-container">
  <% flash.each do |type, message| %>
    <% if type == 'notice' %>
      <div class="notice">
        <%= message %>
      </div>
    <% elsif type == 'alert' %>
      <div class="alert">
        <%= message %>
      </div>
    <% end %>
  <% end %>
</div>

  <nav class="navbar navbar-light mynavbar">
    <div class="d-flex justify-content-center">
      <span class="navbar-brand">oète</span>
      <div class="d-flex justify-content-between">
         <form class="form-inline ml-auto">
           <input class="form-control mr-sm-2 circular-search" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <i class="bi bi-search"></i>
          </button>
        </form>   
      
      </div>
    </div>
    <% if user_signed_in? %> 
     <%= link_to edit_profile_path(current_user) do %>
  <%= image_tag(current_user.image, class: "nav-profile-image") %>
<% end %>
      <%= link_to 'Home', home_path %>
      <%= link_to 'Write a poem', writing_path %>
      <%= link_to 'Profile', profile_path %>
      <%= link_to 'Account settings', edit_user_registration_path %>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
 
    <% else %>
      <div class="d-flex justify-content-center">
        <%= link_to 'Log in', new_user_session_path %>
        <%= link_to 'Sign up', new_user_registration_path %>
      </div>
    <% end %>
  </nav>

  <%= yield %>

  <footer class="text-center text-white" style="background-color: #ABCD78; height: 25px; position: absolute; bottom: 0; width: 100%;">
    <div class="container p-4"></div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 oète.com
    </div>
  </footer>
</body>
</html>